import { PrismaClient } from '../src/generated/prisma';

const prisma = new PrismaClient();

const sampleBooks = [
  // Architecture (10 books)
  {
    id: 'arch-001',
    title: 'The Architecture of Happiness',
    authors: 'Alain de Botton',
    description: 'A philosophical look at how architecture shapes our emotions and well-being.',
    averageRating: 4.1,
    ratingsCount: 1200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'architecture',
  },
  {
    id: 'arch-002',
    title: 'Towards a New Architecture',
    authors: 'Le Corbusier',
    description: 'A seminal text on modern architecture and design principles.',
    averageRating: 4.3,
    ratingsCount: 890,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 22.99,
    category: 'architecture',
  },
  {
    id: 'arch-003',
    title: '101 Things I Learned in Architecture School',
    authors: 'Matthew Frederick',
    description: 'Essential lessons for architecture students presented in a concise format.',
    averageRating: 4.5,
    ratingsCount: 2100,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'architecture',
  },
  {
    id: 'arch-004',
    title: 'A Pattern Language',
    authors: 'Christopher Alexander',
    description: 'Timeless ways of building communities and spaces.',
    averageRating: 4.6,
    ratingsCount: 1500,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 45.99,
    category: 'architecture',
  },
  {
    id: 'arch-005',
    title: 'The Eyes of the Skin',
    authors: 'Juhani Pallasmaa',
    description: 'Architecture and the senses beyond vision.',
    averageRating: 4.4,
    ratingsCount: 780,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'architecture',
  },
  {
    id: 'arch-006',
    title: 'Complexity and Contradiction in Architecture',
    authors: 'Robert Venturi',
    description: 'A gentle manifesto for a non-straightforward architecture.',
    averageRating: 4.2,
    ratingsCount: 650,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 24.99,
    category: 'architecture',
  },
  {
    id: 'arch-007',
    title: 'Architecture: Form, Space, and Order',
    authors: 'Francis D.K. Ching',
    description: 'A comprehensive introduction to architectural design.',
    averageRating: 4.7,
    ratingsCount: 3200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 42.99,
    category: 'architecture',
  },
  {
    id: 'arch-008',
    title: 'Delirious New York',
    authors: 'Rem Koolhaas',
    description: 'A retroactive manifesto for Manhattan.',
    averageRating: 4.3,
    ratingsCount: 980,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 28.99,
    category: 'architecture',
  },
  {
    id: 'arch-009',
    title: 'The Death and Life of Great American Cities',
    authors: 'Jane Jacobs',
    description: 'A revolutionary look at urban planning and city life.',
    averageRating: 4.5,
    ratingsCount: 4100,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'architecture',
  },
  {
    id: 'arch-010',
    title: 'S, M, L, XL',
    authors: 'Rem Koolhaas, Bruce Mau',
    description: 'A massive exploration of architecture and contemporary culture.',
    averageRating: 4.4,
    ratingsCount: 720,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 65.99,
    category: 'architecture',
  },

  // Art & Fashion (10 books)
  {
    id: 'artf-001',
    title: 'The Story of Art',
    authors: 'E.H. Gombrich',
    description: 'One of the most famous and popular books on art ever written.',
    averageRating: 4.6,
    ratingsCount: 5200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 29.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-002',
    title: 'Ways of Seeing',
    authors: 'John Berger',
    description: 'Revolutionary perspectives on viewing and interpreting art.',
    averageRating: 4.5,
    ratingsCount: 3800,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-003',
    title: 'The Fashion Book',
    authors: 'Phaidon Editors',
    description: 'A comprehensive A-Z of fashion designers and brands.',
    averageRating: 4.4,
    ratingsCount: 2100,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 39.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-004',
    title: 'Alexander McQueen: Savage Beauty',
    authors: 'Andrew Bolton',
    description: 'The definitive book on the legendary designer.',
    averageRating: 4.8,
    ratingsCount: 1800,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 49.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-005',
    title: 'Color and Light: A Guide for the Realist Painter',
    authors: 'James Gurney',
    description: 'Essential techniques for painting with color and light.',
    averageRating: 4.7,
    ratingsCount: 2900,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 24.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-006',
    title: 'Steal Like an Artist',
    authors: 'Austin Kleon',
    description: '10 things nobody told you about being creative.',
    averageRating: 4.3,
    ratingsCount: 8500,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 12.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-007',
    title: 'Vogue: The Covers',
    authors: 'Dodie Kazanjian',
    description: 'A stunning collection of iconic Vogue magazine covers.',
    averageRating: 4.6,
    ratingsCount: 1200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 44.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-008',
    title: 'Drawing on the Right Side of the Brain',
    authors: 'Betty Edwards',
    description: 'A revolutionary approach to learning how to draw.',
    averageRating: 4.5,
    ratingsCount: 4200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-009',
    title: 'The Little Dictionary of Fashion',
    authors: 'Christian Dior',
    description: 'An A-Z guide to fashion from the legendary designer.',
    averageRating: 4.4,
    ratingsCount: 980,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'art & fashion',
  },
  {
    id: 'artf-010',
    title: 'The Art Spirit',
    authors: 'Robert Henri',
    description: 'Inspirational notes and advice on art and life.',
    averageRating: 4.6,
    ratingsCount: 1500,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'art & fashion',
  },

  // Biography (10 books)
  {
    id: 'bio-001',
    title: 'Steve Jobs',
    authors: 'Walter Isaacson',
    description: 'The authorized biography of the Apple co-founder.',
    averageRating: 4.5,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'biography',
  },
  {
    id: 'bio-002',
    title: 'Educated',
    authors: 'Tara Westover',
    description: 'A memoir about growing up in a survivalist family and pursuing education.',
    averageRating: 4.7,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'biography',
  },
  {
    id: 'bio-003',
    title: 'Becoming',
    authors: 'Michelle Obama',
    description: 'The memoir of the former First Lady of the United States.',
    averageRating: 4.8,
    ratingsCount: 25000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'biography',
  },
  {
    id: 'bio-004',
    title: 'The Diary of a Young Girl',
    authors: 'Anne Frank',
    description: 'The powerful diary of a Jewish girl hiding during the Holocaust.',
    averageRating: 4.6,
    ratingsCount: 32000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 12.99,
    category: 'biography',
  },
  {
    id: 'bio-005',
    title: 'Long Walk to Freedom',
    authors: 'Nelson Mandela',
    description: 'The autobiography of South Africa\'s first Black president.',
    averageRating: 4.7,
    ratingsCount: 8900,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'biography',
  },
  {
    id: 'bio-006',
    title: 'Einstein: His Life and Universe',
    authors: 'Walter Isaacson',
    description: 'A comprehensive biography of the genius physicist.',
    averageRating: 4.4,
    ratingsCount: 6700,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 21.99,
    category: 'biography',
  },
  {
    id: 'bio-007',
    title: 'The Autobiography of Malcolm X',
    authors: 'Malcolm X, Alex Haley',
    description: 'The powerful life story of the civil rights leader.',
    averageRating: 4.8,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'biography',
  },
  {
    id: 'bio-008',
    title: 'Born a Crime',
    authors: 'Trevor Noah',
    description: 'Stories from a South African childhood during apartheid.',
    averageRating: 4.6,
    ratingsCount: 14000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'biography',
  },
  {
    id: 'bio-009',
    title: 'The Glass Castle',
    authors: 'Jeannette Walls',
    description: 'A remarkable memoir of resilience and redemption.',
    averageRating: 4.5,
    ratingsCount: 11000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'biography',
  },
  {
    id: 'bio-010',
    title: 'Unbroken',
    authors: 'Laura Hillenbrand',
    description: 'The incredible true story of survival, resilience, and redemption.',
    averageRating: 4.7,
    ratingsCount: 16000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'biography',
  },

  // Business (10 books)
  {
    id: 'bus-001',
    title: 'The Lean Startup',
    authors: 'Eric Ries',
    description: 'How today\'s entrepreneurs use continuous innovation to create radically successful businesses.',
    averageRating: 4.2,
    ratingsCount: 8100,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 21.99,
    category: 'business',
  },
  {
    id: 'bus-002',
    title: 'Zero to One',
    authors: 'Peter Thiel',
    description: 'Notes on startups, or how to build the future.',
    averageRating: 4.3,
    ratingsCount: 9200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'business',
  },
  {
    id: 'bus-003',
    title: 'Good to Great',
    authors: 'Jim Collins',
    description: 'Why some companies make the leap and others don\'t.',
    averageRating: 4.4,
    ratingsCount: 7800,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 24.99,
    category: 'business',
  },
  {
    id: 'bus-004',
    title: 'The Innovator\'s Dilemma',
    authors: 'Clayton M. Christensen',
    description: 'When new technologies cause great firms to fail.',
    averageRating: 4.1,
    ratingsCount: 4500,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 22.99,
    category: 'business',
  },
  {
    id: 'bus-005',
    title: 'Thinking, Fast and Slow',
    authors: 'Daniel Kahneman',
    description: 'The two systems that drive the way we think.',
    averageRating: 4.5,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'business',
  },
  {
    id: 'bus-006',
    title: 'The Hard Thing About Hard Things',
    authors: 'Ben Horowitz',
    description: 'Building a business when there are no easy answers.',
    averageRating: 4.6,
    ratingsCount: 6700,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 23.99,
    category: 'business',
  },
  {
    id: 'bus-007',
    title: 'Shoe Dog',
    authors: 'Phil Knight',
    description: 'A memoir by the creator of Nike.',
    averageRating: 4.7,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'business',
  },
  {
    id: 'bus-008',
    title: 'The 7 Habits of Highly Effective People',
    authors: 'Stephen R. Covey',
    description: 'Powerful lessons in personal change.',
    averageRating: 4.4,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'business',
  },
  {
    id: 'bus-009',
    title: 'Start with Why',
    authors: 'Simon Sinek',
    description: 'How great leaders inspire everyone to take action.',
    averageRating: 4.3,
    ratingsCount: 10000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'business',
  },
  {
    id: 'bus-010',
    title: 'Built to Last',
    authors: 'Jim Collins, Jerry I. Porras',
    description: 'Successful habits of visionary companies.',
    averageRating: 4.2,
    ratingsCount: 6400,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 22.99,
    category: 'business',
  },

  // Drama (8 books)
  {
    id: 'dra-001',
    title: 'Hamlet',
    authors: 'William Shakespeare',
    description: 'The timeless tragedy of the Prince of Denmark.',
    averageRating: 4.5,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 9.99,
    category: 'drama',
  },
  {
    id: 'dra-002',
    title: 'A Streetcar Named Desire',
    authors: 'Tennessee Williams',
    description: 'A powerful American drama about desire and desperation.',
    averageRating: 4.3,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 11.99,
    category: 'drama',
  },
  {
    id: 'dra-003',
    title: 'Death of a Salesman',
    authors: 'Arthur Miller',
    description: 'The classic American play about dreams and disillusionment.',
    averageRating: 4.2,
    ratingsCount: 9800,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 10.99,
    category: 'drama',
  },
  {
    id: 'dra-004',
    title: 'The Crucible',
    authors: 'Arthur Miller',
    description: 'A dramatic allegory about McCarthyism set during the Salem witch trials.',
    averageRating: 4.4,
    ratingsCount: 11000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 10.99,
    category: 'drama',
  },
  {
    id: 'dra-005',
    title: 'Waiting for Godot',
    authors: 'Samuel Beckett',
    description: 'A landmark of absurdist drama exploring existence and meaning.',
    averageRating: 4.1,
    ratingsCount: 7500,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 12.99,
    category: 'drama',
  },
  {
    id: 'dra-006',
    title: 'Macbeth',
    authors: 'William Shakespeare',
    description: 'Shakespeare\'s darkest tragedy about ambition and murder.',
    averageRating: 4.6,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 9.99,
    category: 'drama',
  },
  {
    id: 'dra-007',
    title: 'Romeo and Juliet',
    authors: 'William Shakespeare',
    description: 'The world\'s most famous love story and tragedy.',
    averageRating: 4.5,
    ratingsCount: 30000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 9.99,
    category: 'drama',
  },
  {
    id: 'dra-008',
    title: 'The Glass Menagerie',
    authors: 'Tennessee Williams',
    description: 'A memory play about a faded Southern belle and her children.',
    averageRating: 4.3,
    ratingsCount: 8200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 11.99,
    category: 'drama',
  },

  // Fiction (15 books)
  {
    id: 'fic-001',
    title: 'The Great Gatsby',
    authors: 'F. Scott Fitzgerald',
    description: 'A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.',
    averageRating: 4.2,
    ratingsCount: 35000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 12.99,
    category: 'fiction',
  },
  {
    id: 'fic-002',
    title: '1984',
    authors: 'George Orwell',
    description: 'A dystopian novel depicting a totalitarian society under constant surveillance.',
    averageRating: 4.5,
    ratingsCount: 52000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'fiction',
  },
  {
    id: 'fic-003',
    title: 'To Kill a Mockingbird',
    authors: 'Harper Lee',
    description: 'A powerful story of racial injustice and childhood innocence in the American South.',
    averageRating: 4.6,
    ratingsCount: 48000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 13.99,
    category: 'fiction',
  },
  {
    id: 'fic-004',
    title: 'Pride and Prejudice',
    authors: 'Jane Austen',
    description: 'A romantic novel of manners exploring themes of love, marriage, and social class in Regency England.',
    averageRating: 4.4,
    ratingsCount: 42000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 11.99,
    category: 'fiction',
  },
  {
    id: 'fic-005',
    title: 'The Catcher in the Rye',
    authors: 'J.D. Salinger',
    description: 'A controversial novel about teenage rebellion and alienation.',
    averageRating: 4.0,
    ratingsCount: 38000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 12.99,
    category: 'fiction',
  },
  {
    id: 'fic-006',
    title: 'One Hundred Years of Solitude',
    authors: 'Gabriel García Márquez',
    description: 'A landmark of magical realism following the Buendía family.',
    averageRating: 4.5,
    ratingsCount: 21000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'fiction',
  },
  {
    id: 'fic-007',
    title: 'The Lord of the Rings',
    authors: 'J.R.R. Tolkien',
    description: 'The epic fantasy trilogy that defined the genre.',
    averageRating: 4.8,
    ratingsCount: 65000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 29.99,
    category: 'fiction',
  },
  {
    id: 'fic-008',
    title: 'Brave New World',
    authors: 'Aldous Huxley',
    description: 'A dystopian vision of a technologically advanced future society.',
    averageRating: 4.3,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 13.99,
    category: 'fiction',
  },
  {
    id: 'fic-009',
    title: 'The Handmaid\'s Tale',
    authors: 'Margaret Atwood',
    description: 'A chilling dystopian tale of a theocratic society.',
    averageRating: 4.4,
    ratingsCount: 34000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'fiction',
  },
  {
    id: 'fic-010',
    title: 'The Kite Runner',
    authors: 'Khaled Hosseini',
    description: 'A powerful story of friendship and redemption set in Afghanistan.',
    averageRating: 4.6,
    ratingsCount: 42000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'fiction',
  },
  {
    id: 'fic-011',
    title: 'Life of Pi',
    authors: 'Yann Martel',
    description: 'A fantastical adventure of a boy stranded at sea with a Bengal tiger.',
    averageRating: 4.2,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'fiction',
  },
  {
    id: 'fic-012',
    title: 'The Book Thief',
    authors: 'Markus Zusak',
    description: 'A touching story set in Nazi Germany, narrated by Death.',
    averageRating: 4.7,
    ratingsCount: 38000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'fiction',
  },
  {
    id: 'fic-013',
    title: 'The Alchemist',
    authors: 'Paulo Coelho',
    description: 'A philosophical tale about following your dreams.',
    averageRating: 4.3,
    ratingsCount: 45000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 13.99,
    category: 'fiction',
  },
  {
    id: 'fic-014',
    title: 'The Road',
    authors: 'Cormac McCarthy',
    description: 'A post-apocalyptic journey of a father and son.',
    averageRating: 4.1,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'fiction',
  },
  {
    id: 'fic-015',
    title: 'The Night Circus',
    authors: 'Erin Morgenstern',
    description: 'A magical competition between two young illusionists.',
    averageRating: 4.4,
    ratingsCount: 31000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'fiction',
  },

  // Food & Drink (8 books)
  {
    id: 'food-001',
    title: 'Salt, Fat, Acid, Heat',
    authors: 'Samin Nosrat',
    description: 'Mastering the elements of good cooking.',
    averageRating: 4.7,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 28.99,
    category: 'food & drink',
  },
  {
    id: 'food-002',
    title: 'The Joy of Cooking',
    authors: 'Irma S. Rombauer',
    description: 'The classic all-purpose cookbook for every kitchen.',
    averageRating: 4.6,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 32.99,
    category: 'food & drink',
  },
  {
    id: 'food-003',
    title: 'The Food Lab',
    authors: 'J. Kenji López-Alt',
    description: 'Better home cooking through science.',
    averageRating: 4.8,
    ratingsCount: 8900,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 39.99,
    category: 'food & drink',
  },
  {
    id: 'food-004',
    title: 'Kitchen Confidential',
    authors: 'Anthony Bourdain',
    description: 'Adventures in the culinary underbelly.',
    averageRating: 4.5,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'food & drink',
  },
  {
    id: 'food-005',
    title: 'The Omnivore\'s Dilemma',
    authors: 'Michael Pollan',
    description: 'A natural history of four meals.',
    averageRating: 4.4,
    ratingsCount: 11000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'food & drink',
  },
  {
    id: 'food-006',
    title: 'On Food and Cooking',
    authors: 'Harold McGee',
    description: 'The science and lore of the kitchen.',
    averageRating: 4.7,
    ratingsCount: 6500,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 42.99,
    category: 'food & drink',
  },
  {
    id: 'food-007',
    title: 'Essentials of Classic Italian Cooking',
    authors: 'Marcella Hazan',
    description: 'The definitive guide to authentic Italian cuisine.',
    averageRating: 4.8,
    ratingsCount: 9200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 34.99,
    category: 'food & drink',
  },
  {
    id: 'food-008',
    title: 'The Silver Spoon',
    authors: 'Phaidon Press',
    description: 'The comprehensive Italian cookbook.',
    averageRating: 4.6,
    ratingsCount: 5100,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 44.99,
    category: 'food & drink',
  },

  // Health & Wellbeing (10 books)
  {
    id: 'health-001',
    title: 'Atomic Habits',
    authors: 'James Clear',
    description: 'An easy and proven way to build good habits and break bad ones through tiny changes.',
    averageRating: 4.7,
    ratingsCount: 89000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-002',
    title: 'The Body Keeps the Score',
    authors: 'Bessel van der Kolk',
    description: 'Brain, mind, and body in the healing of trauma.',
    averageRating: 4.6,
    ratingsCount: 34000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-003',
    title: 'Why We Sleep',
    authors: 'Matthew Walker',
    description: 'Unlocking the power of sleep and dreams.',
    averageRating: 4.5,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-004',
    title: 'Breath',
    authors: 'James Nestor',
    description: 'The new science of a lost art.',
    averageRating: 4.4,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-005',
    title: 'How Not to Die',
    authors: 'Michael Greger',
    description: 'Discover the foods scientifically proven to prevent and reverse disease.',
    averageRating: 4.6,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-006',
    title: 'The Power of Now',
    authors: 'Eckhart Tolle',
    description: 'A guide to spiritual enlightenment.',
    averageRating: 4.3,
    ratingsCount: 45000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-007',
    title: 'Yoga Anatomy',
    authors: 'Leslie Kaminoff',
    description: 'A comprehensive guide to yoga poses and movements.',
    averageRating: 4.7,
    ratingsCount: 6800,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 24.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-008',
    title: 'The Four Agreements',
    authors: 'Don Miguel Ruiz',
    description: 'A practical guide to personal freedom.',
    averageRating: 4.5,
    ratingsCount: 38000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 12.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-009',
    title: 'Mindfulness in Plain English',
    authors: 'Bhante Henepola Gunaratana',
    description: 'A classic guide to meditation and mindfulness.',
    averageRating: 4.6,
    ratingsCount: 8200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 13.99,
    category: 'health & wellbeing',
  },
  {
    id: 'health-010',
    title: 'The Relaxation and Stress Reduction Workbook',
    authors: 'Martha Davis, Elizabeth Robbins Eshelman',
    description: 'Evidence-based techniques for managing stress and anxiety.',
    averageRating: 4.4,
    ratingsCount: 5600,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 21.99,
    category: 'health & wellbeing',
  },

  // History & Politics (10 books)
  {
    id: 'hist-001',
    title: 'Sapiens',
    authors: 'Yuval Noah Harari',
    description: 'A brief history of humankind exploring how Homo sapiens came to dominate the world.',
    averageRating: 4.5,
    ratingsCount: 67000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'history & politics',
  },
  {
    id: 'hist-002',
    title: 'Guns, Germs, and Steel',
    authors: 'Jared Diamond',
    description: 'The fates of human societies and why some civilizations succeeded.',
    averageRating: 4.3,
    ratingsCount: 42000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'history & politics',
  },
  {
    id: 'hist-003',
    title: 'A People\'s History of the United States',
    authors: 'Howard Zinn',
    description: 'American history from the perspective of ordinary people.',
    averageRating: 4.4,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'history & politics',
  },
  {
    id: 'hist-004',
    title: 'The Sixth Extinction',
    authors: 'Elizabeth Kolbert',
    description: 'An unnatural history of mass extinction.',
    averageRating: 4.2,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'history & politics',
  },
  {
    id: 'hist-005',
    title: '1776',
    authors: 'David McCullough',
    description: 'The pivotal year in American history.',
    averageRating: 4.5,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'history & politics',
  },
  {
    id: 'hist-006',
    title: 'The Rise and Fall of the Third Reich',
    authors: 'William L. Shirer',
    description: 'A comprehensive history of Nazi Germany.',
    averageRating: 4.6,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 24.99,
    category: 'history & politics',
  },
  {
    id: 'hist-007',
    title: 'Team of Rivals',
    authors: 'Doris Kearns Goodwin',
    description: 'The political genius of Abraham Lincoln.',
    averageRating: 4.7,
    ratingsCount: 32000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 21.99,
    category: 'history & politics',
  },
  {
    id: 'hist-008',
    title: 'The Silk Roads',
    authors: 'Peter Frankopan',
    description: 'A new history of the world from the crossroads of civilizations.',
    averageRating: 4.4,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'history & politics',
  },
  {
    id: 'hist-009',
    title: 'SPQR',
    authors: 'Mary Beard',
    description: 'A history of ancient Rome.',
    averageRating: 4.5,
    ratingsCount: 16000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 20.99,
    category: 'history & politics',
  },
  {
    id: 'hist-010',
    title: 'The Cold War',
    authors: 'John Lewis Gaddis',
    description: 'A new history of the decades-long conflict.',
    averageRating: 4.3,
    ratingsCount: 9800,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'history & politics',
  },

  // Humor (6 books)
  {
    id: 'humor-001',
    title: 'The Hitchhiker\'s Guide to the Galaxy',
    authors: 'Douglas Adams',
    description: 'A comedic science fiction series about space travel and the meaning of life.',
    averageRating: 4.6,
    ratingsCount: 52000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'humor',
  },
  {
    id: 'humor-002',
    title: 'Good Omens',
    authors: 'Terry Pratchett, Neil Gaiman',
    description: 'A hilarious apocalyptic comedy about an angel and a demon.',
    averageRating: 4.5,
    ratingsCount: 38000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'humor',
  },
  {
    id: 'humor-003',
    title: 'Catch-22',
    authors: 'Joseph Heller',
    description: 'A satirical novel about war and bureaucracy.',
    averageRating: 4.3,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'humor',
  },
  {
    id: 'humor-004',
    title: 'Me Talk Pretty One Day',
    authors: 'David Sedaris',
    description: 'Hilarious essays about life, family, and learning French.',
    averageRating: 4.4,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 13.99,
    category: 'humor',
  },
  {
    id: 'humor-005',
    title: 'Bossypants',
    authors: 'Tina Fey',
    description: 'Hilarious memoir from the comedy writer and actress.',
    averageRating: 4.2,
    ratingsCount: 32000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'humor',
  },
  {
    id: 'humor-006',
    title: 'The Princess Bride',
    authors: 'William Goldman',
    description: 'A witty fairy tale about true love and high adventure.',
    averageRating: 4.7,
    ratingsCount: 45000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'humor',
  },

  // Poetry (7 books)
  {
    id: 'poetry-001',
    title: 'The Sun and Her Flowers',
    authors: 'Rupi Kaur',
    description: 'A collection of poetry about growth, healing, and femininity.',
    averageRating: 4.5,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'poetry',
  },
  {
    id: 'poetry-002',
    title: 'Milk and Honey',
    authors: 'Rupi Kaur',
    description: 'Poetry about survival, love, loss, and femininity.',
    averageRating: 4.4,
    ratingsCount: 42000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 13.99,
    category: 'poetry',
  },
  {
    id: 'poetry-003',
    title: 'The Complete Poems of Emily Dickinson',
    authors: 'Emily Dickinson',
    description: 'The collected works of one of America\'s greatest poets.',
    averageRating: 4.6,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'poetry',
  },
  {
    id: 'poetry-004',
    title: 'Leaves of Grass',
    authors: 'Walt Whitman',
    description: 'The masterwork of American poetry.',
    averageRating: 4.5,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 12.99,
    category: 'poetry',
  },
  {
    id: 'poetry-005',
    title: 'The Waste Land',
    authors: 'T.S. Eliot',
    description: 'A landmark modernist poem about disillusionment.',
    averageRating: 4.3,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 9.99,
    category: 'poetry',
  },
  {
    id: 'poetry-006',
    title: 'The Prophet',
    authors: 'Kahlil Gibran',
    description: 'Poetic essays on love, life, and spirituality.',
    averageRating: 4.7,
    ratingsCount: 32000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 11.99,
    category: 'poetry',
  },
  {
    id: 'poetry-007',
    title: 'Selected Poems',
    authors: 'Pablo Neruda',
    description: 'The essential collection from the Nobel Prize winner.',
    averageRating: 4.6,
    ratingsCount: 8900,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'poetry',
  },

  // Psychology (10 books)
  {
    id: 'psych-001',
    title: 'Thinking, Fast and Slow',
    authors: 'Daniel Kahneman',
    description: 'The two systems that drive the way we think.',
    averageRating: 4.5,
    ratingsCount: 45000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'psychology',
  },
  {
    id: 'psych-002',
    title: 'Man\'s Search for Meaning',
    authors: 'Viktor E. Frankl',
    description: 'A Holocaust survivor\'s profound insights on finding purpose.',
    averageRating: 4.8,
    ratingsCount: 78000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'psychology',
  },
  {
    id: 'psych-003',
    title: 'Influence',
    authors: 'Robert B. Cialdini',
    description: 'The psychology of persuasion.',
    averageRating: 4.4,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'psychology',
  },
  {
    id: 'psych-004',
    title: 'The Power of Habit',
    authors: 'Charles Duhigg',
    description: 'Why we do what we do in life and business.',
    averageRating: 4.3,
    ratingsCount: 38000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'psychology',
  },
  {
    id: 'psych-005',
    title: 'Mindset',
    authors: 'Carol S. Dweck',
    description: 'The new psychology of success.',
    averageRating: 4.4,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'psychology',
  },
  {
    id: 'psych-006',
    title: 'The Interpretation of Dreams',
    authors: 'Sigmund Freud',
    description: 'The foundational text of psychoanalysis.',
    averageRating: 4.2,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'psychology',
  },
  {
    id: 'psych-007',
    title: 'Emotional Intelligence',
    authors: 'Daniel Goleman',
    description: 'Why it can matter more than IQ.',
    averageRating: 4.3,
    ratingsCount: 32000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'psychology',
  },
  {
    id: 'psych-008',
    title: 'Grit',
    authors: 'Angela Duckworth',
    description: 'The power of passion and perseverance.',
    averageRating: 4.2,
    ratingsCount: 24000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'psychology',
  },
  {
    id: 'psych-009',
    title: 'The Art of Thinking Clearly',
    authors: 'Rolf Dobelli',
    description: 'Better thinking through awareness of cognitive biases.',
    averageRating: 4.1,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'psychology',
  },
  {
    id: 'psych-010',
    title: 'Flow',
    authors: 'Mihaly Csikszentmihalyi',
    description: 'The psychology of optimal experience.',
    averageRating: 4.4,
    ratingsCount: 16000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'psychology',
  },

  // Science (10 books)
  {
    id: 'sci-001',
    title: 'A Brief History of Time',
    authors: 'Stephen Hawking',
    description: 'From the Big Bang to black holes.',
    averageRating: 4.4,
    ratingsCount: 38000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'science',
  },
  {
    id: 'sci-002',
    title: 'The Selfish Gene',
    authors: 'Richard Dawkins',
    description: 'A gene-centered view of evolution.',
    averageRating: 4.5,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'science',
  },
  {
    id: 'sci-003',
    title: 'Cosmos',
    authors: 'Carl Sagan',
    description: 'A personal exploration of the universe.',
    averageRating: 4.7,
    ratingsCount: 42000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'science',
  },
  {
    id: 'sci-004',
    title: 'The Origin of Species',
    authors: 'Charles Darwin',
    description: 'The foundation of evolutionary biology.',
    averageRating: 4.6,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'science',
  },
  {
    id: 'sci-005',
    title: 'Astrophysics for People in a Hurry',
    authors: 'Neil deGrasse Tyson',
    description: 'Essential cosmic knowledge explained concisely.',
    averageRating: 4.3,
    ratingsCount: 52000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'science',
  },
  {
    id: 'sci-006',
    title: 'The Double Helix',
    authors: 'James D. Watson',
    description: 'A personal account of the discovery of DNA structure.',
    averageRating: 4.2,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'science',
  },
  {
    id: 'sci-007',
    title: 'The Elegant Universe',
    authors: 'Brian Greene',
    description: 'Superstrings, hidden dimensions, and the quest for ultimate theory.',
    averageRating: 4.4,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'science',
  },
  {
    id: 'sci-008',
    title: 'The Gene',
    authors: 'Siddhartha Mukherjee',
    description: 'An intimate history.',
    averageRating: 4.5,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'science',
  },
  {
    id: 'sci-009',
    title: 'The Structure of Scientific Revolutions',
    authors: 'Thomas S. Kuhn',
    description: 'How scientific paradigms shift.',
    averageRating: 4.3,
    ratingsCount: 9800,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'science',
  },
  {
    id: 'sci-010',
    title: 'Sapiens',
    authors: 'Yuval Noah Harari',
    description: 'A brief history of humankind.',
    averageRating: 4.5,
    ratingsCount: 67000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 18.99,
    category: 'science',
  },

  // Technology (10 books)
  {
    id: 'tech-001',
    title: 'The Pragmatic Programmer',
    authors: 'Andrew Hunt, David Thomas',
    description: 'A comprehensive guide to becoming a better software developer with practical advice and timeless wisdom.',
    averageRating: 4.3,
    ratingsCount: 21000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 39.99,
    category: 'technology',
  },
  {
    id: 'tech-002',
    title: 'Clean Code',
    authors: 'Robert C. Martin',
    description: 'A handbook of agile software craftsmanship teaching how to write code that is clean, maintainable, and testable.',
    averageRating: 4.4,
    ratingsCount: 32000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 44.99,
    category: 'technology',
  },
  {
    id: 'tech-003',
    title: 'The Innovators',
    authors: 'Walter Isaacson',
    description: 'How a group of hackers, geniuses, and geeks created the digital revolution.',
    averageRating: 4.2,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 19.99,
    category: 'technology',
  },
  {
    id: 'tech-004',
    title: 'Code',
    authors: 'Charles Petzold',
    description: 'The hidden language of computer hardware and software.',
    averageRating: 4.6,
    ratingsCount: 8900,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 29.99,
    category: 'technology',
  },
  {
    id: 'tech-005',
    title: 'Algorithms to Live By',
    authors: 'Brian Christian, Tom Griffiths',
    description: 'The computer science of human decisions.',
    averageRating: 4.3,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'technology',
  },
  {
    id: 'tech-006',
    title: 'The Phoenix Project',
    authors: 'Gene Kim, Kevin Behr, George Spafford',
    description: 'A novel about IT, DevOps, and helping your business win.',
    averageRating: 4.5,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 24.99,
    category: 'technology',
  },
  {
    id: 'tech-007',
    title: 'Design Patterns',
    authors: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
    description: 'Elements of reusable object-oriented software.',
    averageRating: 4.4,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 49.99,
    category: 'technology',
  },
  {
    id: 'tech-008',
    title: 'Artificial Intelligence: A Modern Approach',
    authors: 'Stuart Russell, Peter Norvig',
    description: 'The leading textbook in AI.',
    averageRating: 4.5,
    ratingsCount: 6700,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 89.99,
    category: 'technology',
  },
  {
    id: 'tech-009',
    title: 'Cracking the Coding Interview',
    authors: 'Gayle Laakmann McDowell',
    description: '189 programming questions and solutions.',
    averageRating: 4.6,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 34.99,
    category: 'technology',
  },
  {
    id: 'tech-010',
    title: 'The Mythical Man-Month',
    authors: 'Frederick P. Brooks Jr.',
    description: 'Essays on software engineering.',
    averageRating: 4.3,
    ratingsCount: 9200,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 34.99,
    category: 'technology',
  },

  // Travel & Maps (8 books)
  {
    id: 'travel-001',
    title: 'Into the Wild',
    authors: 'Jon Krakauer',
    description: 'The story of Christopher McCandless and his Alaskan odyssey.',
    averageRating: 4.5,
    ratingsCount: 42000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'travel & maps',
  },
  {
    id: 'travel-002',
    title: 'Wild',
    authors: 'Cheryl Strayed',
    description: 'From lost to found on the Pacific Crest Trail.',
    averageRating: 4.3,
    ratingsCount: 38000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'travel & maps',
  },
  {
    id: 'travel-003',
    title: 'The Geography of Bliss',
    authors: 'Eric Weiner',
    description: 'One grump\'s search for the happiest places in the world.',
    averageRating: 4.2,
    ratingsCount: 12000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'travel & maps',
  },
  {
    id: 'travel-004',
    title: 'A Walk in the Woods',
    authors: 'Bill Bryson',
    description: 'Rediscovering America on the Appalachian Trail.',
    averageRating: 4.4,
    ratingsCount: 28000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 15.99,
    category: 'travel & maps',
  },
  {
    id: 'travel-005',
    title: 'In a Sunburned Country',
    authors: 'Bill Bryson',
    description: 'A hilarious journey through Australia.',
    averageRating: 4.5,
    ratingsCount: 22000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 16.99,
    category: 'travel & maps',
  },
  {
    id: 'travel-006',
    title: 'The Lost City of Z',
    authors: 'David Grann',
    description: 'A tale of deadly obsession in the Amazon.',
    averageRating: 4.3,
    ratingsCount: 18000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 17.99,
    category: 'travel & maps',
  },
  {
    id: 'travel-007',
    title: 'Vagabonding',
    authors: 'Rolf Potts',
    description: 'An uncommon guide to the art of long-term world travel.',
    averageRating: 4.4,
    ratingsCount: 8900,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 14.99,
    category: 'travel & maps',
  },
  {
    id: 'travel-008',
    title: 'Atlas Obscura',
    authors: 'Joshua Foer, Dylan Thuras, Ella Morton',
    description: 'An explorer\'s guide to the world\'s hidden wonders.',
    averageRating: 4.6,
    ratingsCount: 15000,
    thumbnailUrl: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    price: 29.99,
    category: 'travel & maps',
  },
];

async function main() {
  console.log('🌱 Starting database seed...');

  // Clear existing books (optional - remove if you want to keep existing data)
  console.log('🗑️  Clearing existing books...');
  await prisma.book.deleteMany();

  // Create books
  console.log('📚 Creating books...');
  for (const book of sampleBooks) {
    await prisma.book.create({
      data: book,
    });
    console.log(`  ✓ Created: ${book.title} (${book.category})`);
  }

  console.log(`\n✅ Seed completed! Created ${sampleBooks.length} books across all categories.`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:');
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
